

namespace NFCombat2.Common.Enums
{
    public enum ItemType
    {
        Item,
        //equipment
        TacticalGlasses,
        GasMask,
        GrenadeLauncher,
        Shuttle,
        ArmoredVest,
        CamouflageSuit,
        Helmet,
        NuclearWarhead,
        LaserSight,
        BarrelExtender,
        GasOperatedReloadingSystem,
        ChameleonSkin,
        Bundle,

        //active equipment
        ArcWhip,
        AutomatedMedKit,
        HandGrenade,
        PortableSurgicalLaser,
        RocketPropelledFishingPole,
        PneumaticDrill,
        PlatinumPhial,

        //active item
        FuelCellBattery,
        ChargedGrapheneRod,
        RottingFruit,
        SackOfAcorns,
        Antivenom,
        SackOfNeutralSoil,
        HerbalTincture,
        BruteLeafExtract,
        SelfRepairFoam,
        SodiumThiosulfateSerum,
        PotassiumIodideTablets,
        Wrench,
        AromaticSaltSolution,
        PortableEnvoronmentalSuit,
        
        //weapon
        PlasmaRapier,
        QuantumMagnumParadox,
        Knife,
        Flamethrower,
        ConfiscatedRifle,
        SemiautomaticPistol,
        RailGun,
        TrainingRifle,
        TrainingSniperRifle,
        JawHooks,
        SniperPlasmaThrower,
        CombatKnife,
        AutomaticPistol,
        AssaultRifle,
        Shotgun,
        PlasmaMinigun,
        ShockBaton,
        CurvedTail,
        PlasmaThrower,
        ShortBarrelPlasmaThrower,
        DoubleBarrelShotgun,
        WrenchWeapon,
        JaggedDagger,
        Torch,
        Chain,
        SteelBar,
        SteelPlate,
        CalibratedRifle,
        SmallCaliberPistol,
        RocketLauncher,
        Minigun,
        GravityModulator,
        EMShield,
        SemiautomaticBeretta,
        BoltActionCarbine,
        SniperRifle,
        Magnum,
        SawnOffShotgun,

        //generic items
        CopperDiadem,
        Rope,
        AutomaticSaw,
        FoodCapsules,
        GrapheneRod,
        AluminiumCanister,
        CrystalNecklace,
        FuelCanister,
        MagnetDiscs,
        IceSpark

    }
}
