

namespace NFCombat2.Common.Enums
{
    public enum MessageType
    {
        None,
        //combat effect messages
        BonusActionMessage,
        GuaranteedCritsMessage,
        DamageMessage,
        CritMessage,
        MissMessage,
        DamageAoeMessage,
        TakeDamageMessage,
        FreezeMessage,
        FreezeAoeMessage,
        IsFrozenMessage,
        HealMessage,
        ChangeDistanceMessage,
        Draw,
        PathogenDecrease,
        PathogenIncrease,
        IonizationDecrease,
        IonizationIncrease,
        StrengthIncrease,
        TraumaDecrease,
        TraumaIncrease,
        OverloadDecrease,
        OverloadIncrease,
        TemporaryStrengthDamage,
        SkillCheckSuccess,
        HoldBreath,
        NoDamage,
        //action messages
        ShootMessage,
        AoeShootMessage,
        AttackMessage,
        SkillCheckRocks,
        SkillCheckRiver,
        SkillCheckDoor,
        SkillCheckPanel,
        SkillCheckSwamp,
        UseProgramMessage,
        ProgramHealMessage,
        ProgramFreezeMessage,
        ProgramDamageMessage,
        ProgramBonusActionmessage,
        ProgramCritMessage,
        ProgramDisableTentacleMessage,
        ProgramNoEffect,
        LearnProgram,
        UseItemMessage,
        UseItemWithQuantityMessage,
        UseTechniqueMessage,
        MoveCloserMessage,
        MovePassMessage,
        ActionPassMessage,
        EnemyPushedBackMessage,
        BackFlipMessage,
        PrimalInstinctHealmessage,
        ComboDamage,
        WonRoundsCount,
        //enemy messages
        EnemyMoveMessage,
        EnemyMovePassMessage,
        EnemyMoveAwayMessage,
        EnemyShootMessage,
        EnemyAttackMessage,
        EnemyDefeatedMessage,
        EnemyDamageMessage,
        EnemyChangeDistanceMessage,
        EnemyCritMessage,
        EnemyMissMessage,
        SwampAttack,
        SpawnTentacle,
        TraumaTentacleAttack,
        TraumaTentacleMiss,
        PathogenTentacleAttack,
        PathogenTentacleMiss,
        IonizationTentacleAttack,
        IonizationTentacleMiss,
        //item messages
        UseMedkit,
        MaxOverloadIncrease,
        FuelIncrease,
        SteelPlateAbsorb,
        ProtectedFromMaser,
        NoEffect,
        PoleMoveCloser,
        PoleMoveFurther,
        EquippedToWeapon,
        UnequippedFromWeapon,
        WrenchThrow,
        GasMaskProteced,
        
        
    }
}
