

using NFCombat2.Common.Enums;

namespace NFCombat2.Common.AppConstants
{
    public static class EnemyNames
    {
        public static Dictionary<EnemyType, string> EnglishEnemies = new Dictionary<EnemyType, string>()
        {
            //{EnemyType.RegularBrute, "Regular Brute" },
            //{EnemyType.RegularBrute, "Regular Brute" }
            {EnemyType.RegularBrute, "Regular Brute" },
            {EnemyType.PaplacidGuard, "Paplacid Guard" },
            {EnemyType.RegularMeiCin, "Regular MeiCin" },
            {EnemyType.AlienAssassin, "Alien Assassin" },
            {EnemyType.AlienAttacker, "Alien Attacker" },
            {EnemyType.NephropidCommando, "Nephropid Commando" },
            {EnemyType.AlienGuardA, "Alien Guard" },
            {EnemyType.HologramBrute, "Hologram Brute" },
            {EnemyType.InjuredMeiCin, "Injured MeiCin" },
            {EnemyType.SwampFoliage, "Swamp Foliage" },
            {EnemyType.DesertWormA, "Desert Worm" },
            {EnemyType.FelinterRookie, "Felinter Rookie" },
            {EnemyType.PileOfRocks, "Pile Of Rocks" },
            {EnemyType.UndergroundRiver, "Underground River" },
            {EnemyType.LtSide, "LtSide" },
            {EnemyType.DarkPaplacid, "Dark Paplacid" },
            {EnemyType.MetalPanel, "Metal Panel" },
            {EnemyType.StripedBeast, "Striped Beast" },
            {EnemyType.VespisoidFugitive, "Vespisoid Fugitive" },
            {EnemyType.FirstPaplacidA, "First Paplacid" },
            {EnemyType.SecondPaplacidA, "Second Paplacid" },
            {EnemyType.ThirdPaplacidA, "Third Paplacid" },
            {EnemyType.FourthPaplacidA, "Fourth Paplacid" },
            {EnemyType.FirstPaplacidB, "Paplacid" },
            {EnemyType.SecondPaplacidB, "Paplacid" },
            {EnemyType.YoungDesertWorm, "Young Desert Worm" },
            {EnemyType.AlienPilot, "Alien Pilot" },
            {EnemyType.Sniper, "Sniper" },
            {EnemyType.AlienGuardB, "Alien Guard" },
            {EnemyType.AlientShooter, "Alient Shooter" },
            {EnemyType.AlienLeader, "Alien Leader" },
            {EnemyType.MetalDoor, "Metal Door" },
            {EnemyType.NephropidMechanic, "Nephropid Mechanic" },
            {EnemyType.FelinterMechanic, "Felinter Mechanic" },
            {EnemyType.AlienSentinel, "Alien Sentinel" },
            {EnemyType.GuardRobotAlpha, "Guard Robot Alpha" },
            {EnemyType.GuardRobotBeta, "Guard Robot Beta" },
            {EnemyType.GuardRobotGamma, "Guard Robot Gamma" },
            {EnemyType.UniformedAlien, "Uniformed Alien" },
            {EnemyType.AlienWarden, "Alien Warden" },
            {EnemyType.DefenseSystem, "Defense System" },
            {EnemyType.AlienGuardC, "Alien Guard" },
            {EnemyType.DesertWormB, "Desert Worm" },
            {EnemyType.AgentZorgy, "Agent Zorgy" },
            {EnemyType.MotivatedAlienPursuer, "Motivated Alien Pursuer" },
            {EnemyType.DefenseGun, "Defense Gun" },
            {EnemyType.FelinterWarrior, "Felinter Warrior" },
            {EnemyType.CommanderKabuto, "Commander Kabuto" },
            {EnemyType.DesertWormC, "Desert Worm" },
            {EnemyType.TraumaTentacle, "Cable Tentacle (Metal Hand)" },
            {EnemyType.IonizationTentacle, "Cable Tentacle (Vents)" },
            {EnemyType.PathogenTentacle, "Cable Tentacle (Amonia Maser)" }
        };

        public static Dictionary<EnemyType, string> BulgarianEnemies = new Dictionary<EnemyType, string>()

        {
            //{EnemyType.RegularBrute, "" },
            //{EnemyType.RegularBrute, "Regular Brute" }
            {EnemyType.RegularBrute, " Редови бруут" },
            {EnemyType.PaplacidGuard, "Паплацид пазач" },
            {EnemyType.RegularMeiCin, "Редови мей‘цин" },
            {EnemyType.AlienAssassin, "Извънземен убиец" },
            {EnemyType.AlienAttacker, "Извънземен нападател" },
            {EnemyType.NephropidCommando, "Нефропид командос" },
            {EnemyType.AlienGuardA, "Извънземен пазач" },
            {EnemyType.HologramBrute, "Холограмен бруут" },
            {EnemyType.InjuredMeiCin, "Ранен мей‘цин" },
            {EnemyType.SwampFoliage, "Блатна растителност" },
            {EnemyType.DesertWormA, "Червей пустиняк" },
            {EnemyType.FelinterRookie, "Фелинтер новобранец" },
            {EnemyType.PileOfRocks, "Купчина камъни" },
            {EnemyType.UndergroundRiver, "Подземна река" },
            {EnemyType.LtSide, "Лейтанант Сайд" },
            {EnemyType.DarkPaplacid, "Мургав паплацид" },
            {EnemyType.MetalPanel, "Метален панел" },
            {EnemyType.StripedBeast, "Ивичест звяр" },
            {EnemyType.VespisoidFugitive, "Весписоид беглец" },
            {EnemyType.FirstPaplacidA, "Първи паплацид" },
            {EnemyType.SecondPaplacidA, "Втори паплацид" },
            {EnemyType.ThirdPaplacidA, "Трети паплацид" },
            {EnemyType.FourthPaplacidA, "Четвърти Паплацид" },
            {EnemyType.FirstPaplacidB, "Първи паплацид" },
            {EnemyType.SecondPaplacidB, "Втори паплацид" },
            {EnemyType.YoungDesertWorm, "Млад червей пустиняк" },
            {EnemyType.AlienPilot, "Извънземен пилот" },
            {EnemyType.Sniper, "Снайперист" },
            {EnemyType.AlienGuardB, "Извънземен пазач" },
            {EnemyType.AlientShooter, "Извънземен стрелец" },
            {EnemyType.AlienLeader, "Извънземен водач" },
            {EnemyType.MetalDoor, "Метална врата" },
            {EnemyType.NephropidMechanic, "Нефорпид механик" },
            {EnemyType.FelinterMechanic, "Фелинтер механик" },
            {EnemyType.AlienSentinel, "Извънземен страж" },
            {EnemyType.GuardRobotAlpha, "Охранителен робот Алфа" },
            {EnemyType.GuardRobotBeta, "Охранителен робот Бета" },
            {EnemyType.GuardRobotGamma, "Охранителен робот Гама" },
            {EnemyType.UniformedAlien, "Униформен извънземен" },
            {EnemyType.AlienWarden, "Извънземен охранител" },
            {EnemyType.DefenseSystem, "Отбранителна установка" },
            {EnemyType.AlienGuardC, "Извънземен пазач" },
            {EnemyType.DesertWormB, "Червей пустиняк" },
            {EnemyType.AgentZorgy, "Агент Зорги" },
            {EnemyType.MotivatedAlienPursuer, "Надъхан извънземен преследвач" },
            {EnemyType.DefenseGun, "Защитна картечница" },
            {EnemyType.FelinterWarrior, "Фелинтер воин" },
            {EnemyType.CommanderKabuto, "Командир Кабуто" },
            {EnemyType.DesertWormC, "Червей пустиняк" },
            {EnemyType.TraumaTentacle, "Кабел пипало (Метална ръка)" },
            {EnemyType.IonizationTentacle, "Кабел пипало (Вентилационни шлюзове)" },
            {EnemyType.PathogenTentacle, "Кабел пипало (Амонячен мазер)" }

        };
    }
}
