

using NFCombat2.Common.Enums;

namespace NFCombat2.Common.AppConstants
{
    public static class ItemNames
    {
        public static Dictionary<ItemType, string> EnglishItems = new Dictionary<ItemType, string>
        {
            {ItemType.TacticalGlasses, "Tactical Glasses" },
            {ItemType.GasMask, "Gas Mask" },
            {ItemType.GrenadeLauncher, "Grenade Launcher" },
            {ItemType.Shuttle, "Ship keys" },
            {ItemType.ArmoredVest, "Armored Vest" },
            {ItemType.CamouflageSuit, "Camouflage Suit" },
            {ItemType.Helmet, "Helmet" },
            {ItemType.NuclearWarhead, "Nuclear Warhead" },
            {ItemType.LaserSight, "Laser Sight" },
            {ItemType.BarrelExtender, "Barrel Extender" },
            {ItemType.GasOperatedReloadingSystem, "Gas Operated Reloading System" },
            {ItemType.ChameleonSkin, "Chameleon Skin" },
            {ItemType.Bundle, "Bundle" },
            {ItemType.CombatSuit, "Combat Suit" },

            {ItemType.ArcWhip, "Arc Whip" },
            {ItemType.AutomatedMedKit, "Automated MedKit" },
            {ItemType.HandGrenade, "Hand Grenade" },
            {ItemType.PortableSurgicalLaser, "Portable Surgical Laser" },
            {ItemType.RocketPropelledFishingPole, "Rocket Propelled Fishing Pole" },
            {ItemType.PneumaticDrill, "Pneumatic Drill" },
            {ItemType.PlatinumPhial, "Platinum Phial" },

            {ItemType.FuelCellBattery, "Fuel Cell Battery" },
            {ItemType.ChargedGrapheneRod, "Charged Graphene Rod" },
            {ItemType.RottingFruit, "Rotting Fruit" },
            {ItemType.SackOfAcorns, "Sack Of Acorns" },
            {ItemType.Antivenom, "Antivenom" },
            {ItemType.SackOfNeutralSoil, "Sack Of Neutral Soil" },
            {ItemType.HerbalTincture, "Herbal Tincture" },
            {ItemType.BruteLeafExtract, "Brute Leaf Extract" },
            {ItemType.SelfRepairFoam, "Self Repair Foam" },
            {ItemType.SodiumThiosulfateSerum, "Sodium Thiosulfate Serum" },
            {ItemType.PotassiumIodideTablets, "Potassium Iodide Tablets" },
            {ItemType.Wrench, "Wrench" },
            {ItemType.AromaticSaltSolution, "Aromatic Salt Solution" },
            {ItemType.PortableEnvironmentalSuit, "Portable Environmental Suit" },

            {ItemType.PlasmaRapier, "Plasma Rapier" },
            {ItemType.QuantumMagnumParadox, "Quantum Magnum Paradox" },
            {ItemType.Knife, "Knife" },
            {ItemType.Flamethrower, "Flamethrower" },
            {ItemType.ConfiscatedRifle, "Confiscated Rifle" },
            {ItemType.SemiautomaticPistol, "Gas Pistol" },
            {ItemType.RailGun, "Rail Gun" },
            {ItemType.TrainingRifle, "Training Rifle" },
            {ItemType.TrainingSniperRifle, "Training Sniper Rifle" },
            {ItemType.JawHooks, "Jaw Hooks" },
            {ItemType.SniperPlasmaThrower, "Sniper Plasma Thrower" },
            {ItemType.CombatKnife, "Combat Knife" },
            {ItemType.AutomaticPistol, "Automatic Pistol" },
            {ItemType.AssaultRifle, "Assault Rifle" },
            {ItemType.Shotgun, "Shotgun" },
            {ItemType.HuntingShotgun, "Hunting Shotgun" },
            {ItemType.PlasmaMinigun, "Plasma Minigun" },
            {ItemType.ShockBaton, "Shock Baton" },
            {ItemType.CurvedTail, "Curved Tail" },
            {ItemType.PlasmaThrower, "Plasma Thrower" },
            {ItemType.ShortBarrelPlasmaThrower, "Short Barrel Plasma Thrower" },
            {ItemType.DoubleBarrelShotgun, "Double Barrel Shotgun" },
            {ItemType.WrenchWeapon, "Wrench Weapon" },
            {ItemType.JaggedDagger, "Jagged Dagger" },
            {ItemType.Torch, "Torch" },
            {ItemType.Chain, "Chain" },
            {ItemType.SteelBar, "Steel Bar" },
            {ItemType.SteelPlate, "Steel Plate" },
            {ItemType.CalibratedRifle, "Calibrated Rifle" },
            {ItemType.SmallCaliberPistol, "Small Caliber Pistol" },
            {ItemType.RocketLauncher, "Rocket Launcher" },
            {ItemType.MachineGun, "Machine Gun" },
            {ItemType.GravityModulator, "Gravity Modulator" },
            {ItemType.EMShield, "EM Shield" },
            {ItemType.SemiautomaticBeretta, "Semiautomatic Pistol" },
            {ItemType.BoltActionCarbine, "Bolt Action Carbine" },
            {ItemType.SniperRifle, "Sniper Rifle" },
            {ItemType.Magnum, "Magnum" },
            {ItemType.SawnOffShotgun, "Sawn Off Shotgun" },

            {ItemType.CopperDiadem, "Copper Diadem" },
            {ItemType.Rope, "Rope" },
            {ItemType.AutomaticSaw, "Automatic Saw" },
            {ItemType.FoodCapsules, "Food Capsules" },
            {ItemType.GrapheneRod, "Graphene Rod" },
            {ItemType.AluminiumCanister, "Aluminium Canister" },
            {ItemType.CrystalNecklace, "Crystal Necklace" },
            {ItemType.FuelCanister, "Fuel Canister" },
            {ItemType.MagnetDiscs, "Magnet Discs" },
            {ItemType.IceSpark, "Ice Spark" },

            {ItemType.KabutoMainHand, "Plasma Minigun" },
            {ItemType.KabutoOffHand, " Long Barrel Plasma Minigun" },


        };

        public static Dictionary<ItemType, string> BulgarianItems = new Dictionary<ItemType, string>

        {

            {ItemType.TacticalGlasses, "Тактически очила" },
            {ItemType.GasMask, "Противогаз" },
            {ItemType.GrenadeLauncher, "Подстволен гранатомет" },
            {ItemType.Shuttle, "Корабни ключове" },
            {ItemType.ArmoredVest, "Бронежилетка" },
            {ItemType.CamouflageSuit, "Камуфлажен костюм" },
            {ItemType.Helmet, "Каска" },
            {ItemType.NuclearWarhead, "Ядрена бойна глава" },
            {ItemType.LaserSight, "Лазерен мерник" },
            {ItemType.BarrelExtender, "Удължител за цевта" },
            {ItemType.GasOperatedReloadingSystem, "Газово-възвратен механизъм" },
            {ItemType.ChameleonSkin, "Хамелеонова кожа" },
            {ItemType.Bundle, "Вързоп" },
            {ItemType.CombatSuit, "Боен костюм" },

            {ItemType.ArcWhip, "Електродъгов камшик" },
            {ItemType.AutomatedMedKit, "Автоматизиран медицински комплект" },
            {ItemType.HandGrenade, "Ръчна граната" },
            {ItemType.PortableSurgicalLaser, "Портативен хирургически лазер" },
            {ItemType.RocketPropelledFishingPole, "Реактивна въдица" },
            {ItemType.PneumaticDrill, "Пневматичен свредел" },
            {ItemType.PlatinumPhial, "Платинена ампула" },

            {ItemType.FuelCellBattery, "Батерия за горивна клетка" },
            {ItemType.ChargedGrapheneRod, "Зареден графенов прът" },
            {ItemType.RottingFruit, "Леко загнил ароматен плод" },
            {ItemType.SackOfAcorns, "Кесийка с жълъди от бладен дъб" },
            {ItemType.Antivenom, "Противоотрова" },
            {ItemType.SackOfNeutralSoil, "Торбичка с електронеутрална пръст" },
            {ItemType.HerbalTincture, "Билкова тинктура" },
            {ItemType.BruteLeafExtract, "Екстракт от бруутово биле" },
            {ItemType.SelfRepairFoam, "Пяна /“Поправи се сам/“" },
            {ItemType.SodiumThiosulfateSerum, "Серум с натриев тиосулфат" },
            {ItemType.PotassiumIodideTablets, "Таблетки калиев йодид" },
            {ItemType.Wrench, "Гаечен ключ" },
            {ItemType.AromaticSaltSolution, "Разтвор на ароматни соли" },
            {ItemType.PortableEnvironmentalSuit, "Портативен Скафандър" },

            {ItemType.PlasmaRapier, "Плазмена рапира" },
            {ItemType.QuantumMagnumParadox, "Квантов магнум /“Парадокс/“" },
            {ItemType.Knife, "Нож" },
            {ItemType.Flamethrower, "Огнехвъргачка" },
            {ItemType.ConfiscatedRifle, "Конфискувана винтовка" },
            {ItemType.SemiautomaticPistol, "Газов пистолет" },
            {ItemType.RailGun, "Електромагнитно релсово оръдие" },
            {ItemType.TrainingRifle, "Тренировъчна винтовка" },
            {ItemType.TrainingSniperRifle, "Тренировъчен снайпер" },
            {ItemType.JawHooks, "Челюстни куки" },
            {ItemType.SniperPlasmaThrower, "Снайперски плазмомет" },
            {ItemType.CombatKnife, "Боен нож" },
            {ItemType.AutomaticPistol, "Автоматичен пистолет" },
            {ItemType.AssaultRifle, "Щурмова винтовка" },
            {ItemType.Shotgun, "Пушка помпа" },
            {ItemType.HuntingShotgun, "Ловна помпа" },
            {ItemType.PlasmaMinigun, "Плазмена картечница" },
            {ItemType.ShockBaton, "Електрошокова палка" },
            {ItemType.CurvedTail, "Сърповидна опашка" },
            {ItemType.PlasmaThrower, "Плазмомет" },
            {ItemType.ShortBarrelPlasmaThrower, "Късоцевен плазмомет" },
            {ItemType.DoubleBarrelShotgun, "Двуцевна помпа" },
            {ItemType.WrenchWeapon, "Гаечен ключ" },
            {ItemType.JaggedDagger, "Назъбена кама" },
            {ItemType.Torch, "Горелка" },
            {ItemType.Chain, "Синджир" },
            {ItemType.SteelBar, "Стоманен профил" },
            {ItemType.SteelPlate, "Стоманена плочка" },
            {ItemType.CalibratedRifle, "Калибрирана винтовка" },
            {ItemType.SmallCaliberPistol, "Малокалибрен пистолет" },
            {ItemType.RocketLauncher, "Ракетна базука" },
            {ItemType.MachineGun, "Скорострелна картечница" },
            {ItemType.GravityModulator, "Гравитационен модулатор" },
            {ItemType.EMShield, "Електромагнитен щит" },
            {ItemType.SemiautomaticBeretta, "Полуавтоматичен пистолет" },
            {ItemType.BoltActionCarbine, "Болтова карабина" },
            {ItemType.SniperRifle, "Снайпер" },
            {ItemType.Magnum, "Магнум" },
            {ItemType.SawnOffShotgun, "Късоцевна помпа" },

            {ItemType.CopperDiadem, "Медна диадема" },
            {ItemType.Rope, "Въже" },
            {ItemType.AutomaticSaw, "Автоматичен трион" },
            {ItemType.FoodCapsules, "Хранителни капсули" },
            {ItemType.GrapheneRod, "Графенов прът" },
            {ItemType.AluminiumCanister, "Алуминиева туба" },
            {ItemType.CrystalNecklace, "Кристална огърлица" },
            {ItemType.FuelCanister, "Туба с гориво" },
            {ItemType.MagnetDiscs, "Магнитни дискове" },
            {ItemType.IceSpark, "Ледена искрица" },

            {ItemType.KabutoMainHand, "Плазмена картечница" },
            {ItemType.KabutoOffHand, "Дългоцевна плазмена картечница" },
        };
    }
}
