

using NFCombat2.Common.Enums;

namespace NFCombat2.Common.AppConstants
{
    public static class ItemDescriptions
    {
        public static Dictionary<ItemType, string> EnglishItemDescriptions = new Dictionary<ItemType, string>
        {
            {ItemType.TacticalGlasses, " Increase your weapons' accuracy by one" },
            {ItemType.GasMask, "Provides protection from poisonous gases." },
            {ItemType.GrenadeLauncher, "The grenade launcher increases the damage of the weapon it´s attached to by one die" },
            {ItemType.Shuttle, "A small yet reliable shuttle suited for short interplanetary flights." },
            {ItemType.ArmoredVest, "Increases your maximum health by 5 points." },
            {ItemType.CamouflageSuit, "Lowers your opponents’ accuracy by one level (minimum E)." },
            {ItemType.Helmet, "When an opponent is to deal double damage to you, do not double the result." },
            {ItemType.NuclearWarhead, "\"Encapsulated destruction is best left encapsulated!\" - Bon Gess" },
            {ItemType.LaserSight, "Increases the accuracy of the weapon it's attached to by one level (maximum S). " },
            {ItemType.BarrelExtender, "Increasts the range of the weapon its attached to by 15 meters." },
            {ItemType.GasOperatedReloadingSystem, "Allows an extra shot per turn with the weapon it's attached to." },
            {ItemType.ChameleonSkin, "Reduces your opponents' accuracy by one level (minimum E) " },
            {ItemType.Bundle, "Can hold up to three items." },
            {ItemType.CombatSuit, "Increases your Strenght by 5 while you´re wearing it." },

            {ItemType.ArcWhip, "Melts the circuit boards of almost any machine. You can use it by adding 100 to the model number of the target and turning to the corresponding section. " },
            {ItemType.AutomatedMedKit, "The kit can be used once, including during combat, restoring up to 3 dice of health and reducing your Injuries, Pathogens, and Ionization degrees by one." },
            {ItemType.HandGrenade, "Used once during combat, the grenade deals two dice of damage to all enemies within a 10-meter radius." },
            {ItemType.PortableSurgicalLaser, "Holds a single charge that can restore 2 dice of health. The laser cannot be used during combat." },
            {ItemType.RocketPropelledFishingPole, "\"Used once during each combat, the jet hook increases or shortens the distance to your opponent by up to six meters.\r\nYou can also use it outside of combat to access hard-to-reach places or get out of dangerous situations, by adding 50 to the number of the section you're reading. \"" },
            {ItemType.PneumaticDrill, "The drill can crack doors as well as encrypted mechanisms. To use it, add 150 to the object's model number and turn to the resulting section." },
            {ItemType.PlatinumPhial, "Permanently increase your maximum degree of Overload by three. " },

            {ItemType.FuelCellBattery, "You can use the battery any time while you are on a spacecraft such as a shuttle or rocketplane. It will increase the energy capacity (EC) of its fuel cell by 30%." },
            {ItemType.ChargedGrapheneRod, "Used once during combat, it deals 7 dice + 7 damage to all opponents, regardless of distance." },
            {ItemType.RottingFruit, "Restores up to 4 points of health once, except during combat. " },
            {ItemType.SackOfAcorns, "Reduces your Pathogen degree by one, except during combat. " },
            {ItemType.Antivenom, "Reduces your Pathogens degree by one." },
            {ItemType.SackOfNeutralSoil, "Reduces your Ionization degree by one." },
            {ItemType.HerbalTincture, "Restores up to 2 dice of health." },
            {ItemType.BruteLeafExtract, "Increases your Strength by 2 for the duration of one battle." },
            {ItemType.SelfRepairFoam, "Reduces your Injury degree by one." },
            {ItemType.SodiumThiosulfateSerum, "Reduces your Pathogens degree by one." },
            {ItemType.PotassiumIodideTablets, "Reduces your Ionization degree by one." },
            {ItemType.Wrench, "The wrench can fit in the bag as well, and counts as a separate item. During combat, you may throw it once at an opponent within five meters to deal one die of damage." },
            {ItemType.AromaticSaltSolution, "Reduces your current Overload degree by two and increases its maximum degree by one." },
            {ItemType.PortableEnvironmentalSuit, "" },

            {ItemType.PlasmaRapier, "" },
            {ItemType.QuantumMagnumParadox, "" },
            {ItemType.Knife, "" },
            {ItemType.Flamethrower, "The flamethrower damages all enemies in range." },
            {ItemType.ConfiscatedRifle, "" },
            {ItemType.SemiautomaticPistol, "" },
            {ItemType.RailGun, "Whenever you deal double damage to an opponent with the gun, double the result once more." },
            {ItemType.TrainingRifle, "" },
            {ItemType.TrainingSniperRifle, "Has a minimum range of 10 meters." },
            {ItemType.JawHooks, "" },
            {ItemType.SniperPlasmaThrower, "Always deals 20 damage and has a minimal range of 10 meters." },
            {ItemType.CombatKnife, "" },
            {ItemType.AutomaticPistol, "" },
            {ItemType.AssaultRifle, "The rifle's rate of fire allows an extra shot per turn." },
            {ItemType.Shotgun, "" },
            {ItemType.HuntingShotgun, "" },
            {ItemType.PlasmaMinigun, "" },
            {ItemType.ShockBaton, "" },
            {ItemType.CurvedTail, "" },
            {ItemType.PlasmaThrower, "The plasma launcher always deals 10 damage." },
            {ItemType.ShortBarrelPlasmaThrower, "The plasma launcher always deals 10 damage." },
            {ItemType.DoubleBarrelShotgun, "The shotgun deals damage to all enemies in its range." },
            {ItemType.WrenchWeapon, "" },
            {ItemType.JaggedDagger, "" },
            {ItemType.Torch, "The portable flamethrower deals damage to all enemies in its range." },
            {ItemType.Chain, "" },
            {ItemType.SteelBar, "" },
            {ItemType.SteelPlate, "While carrying it, the plate will take all damage from firearms instead of you." },
            {ItemType.CalibratedRifle, "" },
            {ItemType.SmallCaliberPistol, "" },
            {ItemType.RocketLauncher, "" },
            {ItemType.MachineGun, "" },
            {ItemType.GravityModulator, "Carried in one hand, the shield slows the speed of all projectiles, reducing the damage taken from firearms by 3 points." },
            {ItemType.EMShield, "Carried in one hand, the shield creates a force field around its wielder, which reacts to physical contact, repelling the attacker. Whenever you lose health during melee combat, increase the distance to your opponent by one die." },
            {ItemType.SemiautomaticBeretta, "" },
            {ItemType.BoltActionCarbine, "Produces an additional shot when firing." },
            {ItemType.SniperRifle, "The sniper has a minimum range of 10 meters" },
            {ItemType.Magnum, "" },
            {ItemType.SawnOffShotgun, "Each shot deals damage to all enemies in its range." },

            {ItemType.CopperDiadem, "" },
            {ItemType.Rope, "" },
            {ItemType.AutomaticSaw, "" },
            {ItemType.FoodCapsules, "" },
            {ItemType.GrapheneRod, "" },
            {ItemType.AluminiumCanister, "" },
            {ItemType.CrystalNecklace, "" },
            {ItemType.FuelCanister, "" },
            {ItemType.MagnetDiscs, "" },
            {ItemType.IceSpark, "" },

            {ItemType.KabutoMainHand, "" },
            {ItemType.KabutoOffHand, "" },


        };

        public static Dictionary<ItemType, string> BulgarianItemDescriptions = new Dictionary<ItemType, string>
        {
            {ItemType.TacticalGlasses, "Tactical Glasses" },
            {ItemType.GasMask, "Gas Mask" },
            {ItemType.GrenadeLauncher, "Grenade Launcher" },
            {ItemType.Shuttle, "Shuttle" },
            {ItemType.ArmoredVest, "Armored Vest" },
            {ItemType.CamouflageSuit, "Camouflage Suit" },
            {ItemType.Helmet, "Helmet" },
            {ItemType.NuclearWarhead, "Nuclear Warhead" },
            {ItemType.LaserSight, "Laser Sight" },
            {ItemType.BarrelExtender, "Barrel Extender" },
            {ItemType.GasOperatedReloadingSystem, "Gas Operated Reloading System" },
            {ItemType.ChameleonSkin, "Chameleon Skin" },
            {ItemType.Bundle, "Bundle" },
            {ItemType.CombatSuit, "Combat Suit" },

            {ItemType.ArcWhip, "Arc Whip" },
            {ItemType.AutomatedMedKit, "Automated MedKit" },
            {ItemType.HandGrenade, "Hand Grenade" },
            {ItemType.PortableSurgicalLaser, "Portable Surgical Laser" },
            {ItemType.RocketPropelledFishingPole, "Rocket Propelled Fishing Pole" },
            {ItemType.PneumaticDrill, "Pneumatic Drill" },
            {ItemType.PlatinumPhial, "Platinum Phial" },

            {ItemType.FuelCellBattery, "Fuel Cell Battery" },
            {ItemType.ChargedGrapheneRod, "Charged Graphene Rod" },
            {ItemType.RottingFruit, "Rotting Fruit" },
            {ItemType.SackOfAcorns, "Sack Of Acorns" },
            {ItemType.Antivenom, "Antivenom" },
            {ItemType.SackOfNeutralSoil, "Sack Of Neutral Soil" },
            {ItemType.HerbalTincture, "Herbal Tincture" },
            {ItemType.BruteLeafExtract, "Brute Leaf Extract" },
            {ItemType.SelfRepairFoam, "Self Repair Foam" },
            {ItemType.SodiumThiosulfateSerum, "Sodium Thiosulfate Serum" },
            {ItemType.PotassiumIodideTablets, "Potassium Iodide Tablets" },
            {ItemType.Wrench, "Wrench" },
            {ItemType.AromaticSaltSolution, "Aromatic Salt Solution" },
            {ItemType.PortableEnvironmentalSuit, "Portable Environmental Suit" },

            {ItemType.PlasmaRapier, "" },
            {ItemType.QuantumMagnumParadox, "" },
            {ItemType.Knife, "" },
            {ItemType.Flamethrower, "The flamethrower damages all enemies in range." },
            {ItemType.ConfiscatedRifle, "" },
            {ItemType.SemiautomaticPistol, "" },
            {ItemType.RailGun, "Whenever you deal double damage to an opponent with the gun, double the result once more." },
            {ItemType.TrainingRifle, "" },
            {ItemType.TrainingSniperRifle, "" },
            {ItemType.JawHooks, "" },
            {ItemType.SniperPlasmaThrower, "" },
            {ItemType.CombatKnife, "" },
            {ItemType.AutomaticPistol, "" },
            {ItemType.AssaultRifle, "" },
            {ItemType.Shotgun, "" },
            {ItemType.HuntingShotgun, "" },
            {ItemType.PlasmaMinigun, "" },
            {ItemType.ShockBaton, "" },
            {ItemType.CurvedTail, "" },
            {ItemType.PlasmaThrower, "" },
            {ItemType.ShortBarrelPlasmaThrower, "" },
            {ItemType.DoubleBarrelShotgun, "" },
            {ItemType.WrenchWeapon, "" },
            {ItemType.JaggedDagger, "" },
            {ItemType.Torch, "" },
            {ItemType.Chain, "" },
            {ItemType.SteelBar, "" },
            {ItemType.SteelPlate, "" },
            {ItemType.CalibratedRifle, "" },
            {ItemType.SmallCaliberPistol, "" },
            {ItemType.RocketLauncher, "" },
            {ItemType.MachineGun, "" },
            {ItemType.GravityModulator, "" },
            {ItemType.EMShield, "" },
            {ItemType.SemiautomaticBeretta, "" },
            {ItemType.BoltActionCarbine, "" },
            {ItemType.SniperRifle, "" },
            {ItemType.Magnum, "" },
            {ItemType.SawnOffShotgun, "" },

            {ItemType.CopperDiadem, "Copper Diadem" },
            {ItemType.Rope, "Rope" },
            {ItemType.AutomaticSaw, "Automatic Saw" },
            {ItemType.FoodCapsules, "Food Capsules" },
            {ItemType.GrapheneRod, "Graphene Rod" },
            {ItemType.AluminiumCanister, "Aluminium Canister" },
            {ItemType.CrystalNecklace, "Crystal Necklace" },
            {ItemType.FuelCanister, "Fuel Canister" },
            {ItemType.MagnetDiscs, "Magnet Discs" },
            {ItemType.IceSpark, "Ice Spark" },

            {ItemType.KabutoMainHand, "Plasma Minigun" },
            {ItemType.KabutoOffHand, " Long Barrel Plasma Minigun" },


        };
    }
}
