

using NFCombat2.Common.Enums;

namespace NFCombat2.Common.AppConstants
{
    public static class Labels
    {
        public static Dictionary<LabelType, string> EnglishLabels = new Dictionary<LabelType, string>
        {
            {LabelType.ChangeWeaponButton, "Change" },
            {LabelType.EquipNewWeaponButton, "Add" },
            {LabelType.UseItemButton, "Use" },
            {LabelType.AcceptCombatResult, "Accept" },
            {LabelType.RejectCombatResult, "Reject" },
            {LabelType.InvalidEpisodeNumber, "Invalid episode number" },
            {LabelType.CraftButton, "Craft" },
            {LabelType.ConfirmButton, "Confirm Episode" },
            {LabelType.Language, "Choose language" },
            {LabelType.SelectClass, "Choose a class" },
            {LabelType.PlayerName, "Name" },
            {LabelType.PlayerNameHint,"Enter your name here" },
            {LabelType.AddPlayerButton, "Create" },
            {LabelType.CharacterPageTitle, "Character" },
            {LabelType.ChangeProfilePicker, "Switch profile" },
            {LabelType.ChangeClassPicker, "Change class" },
            {LabelType.AddNewProfileButton, "Add new profile" },
            {LabelType.FightPageTitle, "Combat Simulator" },
            {LabelType.NotePageTitle, "Log" },
            {LabelType.InventoryPageTitle, "Inventory" },
            {LabelType.FindEpisodeButton, "Find episode" },
            {LabelType.EpisodeEntryHint, "Enter the fight's episode number" },
            {LabelType.Yes, "Yes" },
            {LabelType.No, "No" },
            {LabelType.RollButton, "Roll" },
            {LabelType.RerollButton, "Reroll" },
            {LabelType.FreeRerollButton, "Reroll (-4)" },
            {LabelType.EntryPlaceholder, "Enter item name" },
            {LabelType.EditorPlaceholder, "Enter text..." },
            {LabelType.TitleEditorPlaceholder, "Title" },
            {LabelType.RollResultFormat, "Result : {0}" },
            {LabelType.ExecuteLabel, "Execute program" },
            {LabelType.EndTurn, "End your turn" },
            {LabelType.ItemChoice, "Choose which item to use" },
            {LabelType.StandardActionChoice, "Choose standard action" },
            {LabelType.BonusActionChoice, "Choose bonus action" },
            {LabelType.ExtraActionChoice, "Choose extra action" },
            {LabelType.MoveActionChoice, "Choose move action" },
            {LabelType.WeaponChoice, "Choose a weapon to shoot with" },
            {LabelType.ModeChoice, "Choose mode" },
            {LabelType.ProgramChoice, "Choose a program to execute" },
            {LabelType.EndOfTurn, "Turn end" },
            {LabelType.Unequip, "Unequip" },
            {LabelType.MeleeTargetChoice, "Choose which enemy to attack" },
            {LabelType.RangedTargetChoice, "Choose which enemy to shoot" },
            {LabelType.ManualProgramCast, "Enter program manually" },
            {LabelType.CharacterTab, "Profile" },
            {LabelType.DiceTab, "Dice" },
            {LabelType.LogTab, "Log" },
            {LabelType.InventoryTab, "Inventory" },
            {LabelType.FightTab, "Fight" },
            {LabelType.ConfirmRoll, "Confirm" },
            {LabelType.AddItemButton, "Add" },
            {LabelType.SaveButton, "Save" },
            {LabelType.NoPlayerName, "Please enter player name" },
            {LabelType.AddedPlayer, "Successfully added {0}" },
            {LabelType.RoundBeginning, "Round {0} beginning." },
            {LabelType.BackButton, "Back" },
        };

        public static Dictionary<LabelType, string> BulgarianLabels = new Dictionary<LabelType, string>
        {
            {LabelType.ChangeWeaponButton, "Смени" },
            {LabelType.EquipNewWeaponButton, "Добави" },
            {LabelType.UseItemButton, "Използвай" },
            {LabelType.AcceptCombatResult, "Приеми" },
            {LabelType.RejectCombatResult, "Откажи" },
            {LabelType.InvalidEpisodeNumber, "Невалиден номер на епизод" },
            {LabelType.CraftButton, "Създай" },
            {LabelType.ConfirmButton, "Потвърди номер на епизод" },
            {LabelType.Language, "Избери език" },
            {LabelType.SelectClass, "Избери клас" },
            {LabelType.PlayerName, "Име" },
            {LabelType.PlayerNameHint,"Въведи името на персонажа" },
            {LabelType.AddPlayerButton, "Създай" },
            {LabelType.CharacterPageTitle, "Персонаж" },
            {LabelType.ChangeProfilePicker, "Смени профила" },
            {LabelType.ChangeClassPicker, "Смени класа" },
            {LabelType.AddNewProfileButton, "Добави нов профил" },
            {LabelType.FightPageTitle, "Симулатор на битка" },
            {LabelType.NotePageTitle, "Дневник" },
            {LabelType.InventoryPageTitle, "Инвентар" },
            {LabelType.FindEpisodeButton, "Открий епизод" },
            {LabelType.EpisodeEntryHint, "Въведи епизода на битката" },
            {LabelType.Yes, "Да" },
            {LabelType.No, "Не" },
            {LabelType.RollButton, "Хвърли" },
            {LabelType.RerollButton, "Хвърли отново" },
            {LabelType.FreeRerollButton, "Хвърли отново (-4)" },
            {LabelType.EntryPlaceholder, "Въведи името на предмета" },
            {LabelType.EditorPlaceholder, "Въведи текст..." },
            {LabelType.TitleEditorPlaceholder, "Заглавие" },
            {LabelType.RollResultFormat, "Резултат : {0}" },
            {LabelType.ExecuteLabel, "Изпълни програмата" },
            {LabelType.EndTurn, "Приключи хода си" },
            {LabelType.ItemChoice, "Избери предмет" },
            {LabelType.StandardActionChoice, "Избери действие" },
            {LabelType.MoveActionChoice, "Избери движение / предмет" },
            {LabelType.BonusActionChoice, "Избери допълнително действие" },
            {LabelType.ExtraActionChoice, "Избери допълнително действие" },
            {LabelType.WeaponChoice, "Избери с кое оръжие да стреляш" },
            {LabelType.ModeChoice, "Избери режим" },
            {LabelType.ProgramChoice, "Избери коя програма да изпълниш" },
            {LabelType.EndOfTurn, "Край на хода" },
            {LabelType.Unequip, "Откачи от оръжието" },
            {LabelType.MeleeTargetChoice, "Избери кого да нападнеш в близък бой" },
            {LabelType.RangedTargetChoice, "Избери по кого да стреляш" },
            {LabelType.ManualProgramCast, "Въведи програмата ръчно" },
            {LabelType.CharacterTab, "Профил" },
            {LabelType.DiceTab, "Зарове" },
            {LabelType.LogTab, "Дневник" },
            {LabelType.InventoryTab, "Инвентар" },
            {LabelType.FightTab, "Битки" },
            {LabelType.ConfirmRoll, "Потвърди" },
            {LabelType.AddItemButton, "Добави" },
            {LabelType.SaveButton, "Запази" },
            {LabelType.NoPlayerName, "Моля въведи името на играча" },
            {LabelType.AddedPlayer, "Успешно добави {0}" },
            {LabelType.RoundBeginning, "Начало на рунд {0}." },
            {LabelType.BackButton, "Назад" },
        };
    }
}
